version: '3'

services:
  admin:
    build:
      context: ../movies_admin/
      dockerfile: ../Deploy/admin/Dockerfile
    depends_on:
      - db
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    env_file:
      - .env

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=cinema
      - POSTGRES_USER=cinema
      - POSTGRES_DB=cinema
    volumes:
      - cinema_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx_site_conf:/etc/nginx/conf.d
      - static_volume:/usr/src/app/staticfiles/
      - media_volume:/usr/src/app/mediafiles/
    depends_on:
      - admin
    ports:
      - 80:80

volumes:
  cinema_data:
  static_volume:
  media_volume:
